"""
Django settings for transanalytics project - production env.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from .base import *


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Email Backend
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Allowed Hosts
ALLOWED_HOSTS = ['transtats-suanand.rhcloud.com']
