# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 11:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('job_type', models.CharField(max_length=200)),
                ('job_start_time', models.DateTimeField()),
                ('job_end_time', models.DateTimeField(null=True)),
                ('job_log_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('job_result', models.NullBooleanField()),
                ('job_remarks', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'ts_jobs',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('locale_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=200, unique=True)),
                ('locale_alias', models.CharField(max_length=50, null=True)),
                ('lang_status', models.BooleanField()),
                ('lang_set', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ts_locales',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=500, unique=True)),
                ('upstream_url', models.URLField(max_length=2000, unique=True)),
                ('transplatform_slug', models.CharField(max_length=400)),
                ('transplatform_url', models.URLField(max_length=500)),
                ('release_streams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=400), default=list, null=True, size=None)),
                ('lang_set', models.CharField(max_length=200)),
                ('transtats_lastupdated', models.DateTimeField(null=True)),
                ('package_details_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('details_json_lastupdated', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ts_packages',
            },
        ),
        migrations.CreateModel(
            name='ReleaseStream',
            fields=[
                ('relstream_id', models.AutoField(primary_key=True, serialize=False)),
                ('relstream_name', models.CharField(max_length=200)),
                ('relstream_slug', models.CharField(max_length=400, unique=True)),
                ('relstream_server', models.URLField(max_length=500, unique=True)),
                ('relstream_built', models.CharField(max_length=200, null=True)),
                ('srcpkg_format', models.CharField(max_length=50, null=True)),
                ('top_url', models.URLField(max_length=500, unique=True)),
                ('web_url', models.URLField(max_length=500, null=True, unique=True)),
                ('krb_service', models.CharField(max_length=200, null=True)),
                ('auth_type', models.CharField(max_length=200, null=True)),
                ('amqp_server', models.CharField(max_length=500, null=True)),
                ('msgbus_exchange', models.CharField(max_length=200, null=True)),
                ('relstream_status', models.BooleanField()),
            ],
            options={
                'db_table': 'ts_relstream',
            },
        ),
        migrations.CreateModel(
            name='SyncStats',
            fields=[
                ('sync_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=500)),
                ('job_uuid', models.UUIDField()),
                ('project_version', models.CharField(max_length=500, null=True)),
                ('stats_raw_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('sync_iter_count', models.IntegerField()),
                ('sync_visibility', models.BooleanField()),
            ],
            options={
                'db_table': 'ts_syncstats',
            },
        ),
        migrations.CreateModel(
            name='TransPlatform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('engine_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('api_url', models.URLField(max_length=500, unique=True)),
                ('platform_slug', models.CharField(max_length=400, unique=True)),
                ('server_status', models.BooleanField()),
                ('projects_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('projects_lastupdated', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ts_transplatform',
            },
        ),
    ]
