# Generated by Django 2.0.8 on 2019-02-07 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181008_0848'),
    ]

    def update_products(apps, schema_editor):

        if not settings.MIGRATE_INITIAL_DATA:
            return

        Product = apps.get_model('dashboard', 'Product')

        if settings.FAS_AUTH:
            Product.objects.filter(product_slug="fedora").update(
                product_url='https://getfedora.org/', msgbus_exchange="fedora-messaging"
            )

    def add_language(apps, schema_editor):

        if not settings.MIGRATE_INITIAL_DATA:
            return

        Language = apps.get_model('dashboard', 'Language')

        if settings.FAS_AUTH:
            Language.objects.create(
                locale_id="eo", lang_name="Esperanto", locale_alias=None, locale_script="Latn", lang_status=True
            )

    def update_language_sets(apps, schema_editor):

        if not settings.MIGRATE_INITIAL_DATA:
            return

        LanguageSet = apps.get_model('dashboard', 'LanguageSet')

        lang_set_ids = "{af_ZA,sq_AL,ar_EG,as_IN,eu_ES,be_BY,bn_BD,bg_BG,my_MM,ca_ES,zh_CN,zh_TW," \
                       "hr_HR,cs_CZ,da_DK,nl_NL,en_GB,fi_FI,fr_FR,fur_IT,gl_ES,de_DE,ka_GE,el_GR," \
                       "gu_IN,he_IL,hi_IN,hu_HU,id_ID,it_IT,ja_JP,kn_IN,kk_KZ,km_KH,ko_KR,lt_LT,mk_MK," \
                       "mai_IN,ms_MY,ml_IN,mr_IN,mn_MN,ne_NP,nb_NO,nn_NO,or_IN,fa_IR,pl_PL,pt_PT,pt_BR," \
                       "pa_IN,pa_PK,ro_RO,ru_RU,sr_RS,sr_RS@latin,gd_GB,si_LK,sk_SK,es_ES,sv_SE,ta_IN," \
                       "te_IN,th_TH,tr_TR,uk_UA,ur_PK,vi_VN,xh_ZA,yo_NG,zu_ZA,eo}" if settings.FAS_AUTH \
            else "{de_DE, es_ES, fr_FR, it_IT, ja_JP, ko_KR, pt_PT, pt_BR, ru_RU, zh_CN, zh_TW}"

        if settings.FAS_AUTH:
            LanguageSet.objects.filter(lang_set_slug="master-set").update(locale_ids=lang_set_ids)
            LanguageSet.objects.filter(lang_set_slug="all-enabled").update(locale_ids=lang_set_ids)

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_api_url',
            field=models.URLField(max_length=500, null=True, verbose_name='Product API URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(max_length=500, null=True, unique=True, verbose_name='Product URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_server',
            field=models.URLField(max_length=500, verbose_name='Product Server'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_url',
            field=models.URLField(max_length=500, verbose_name='Top URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='web_url',
            field=models.URLField(max_length=500, null=True, verbose_name='Web URL'),
        ),
        migrations.RunPython(update_products),
        migrations.RunPython(add_language),
        migrations.RunPython(update_language_sets),
    ]

    def unapply(self, project_state, schema_editor, collect_sql=False):
        pass
