# Generated by Django 2.0.8 on 2019-06-18 11:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190207_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphrule',
            name='rule_build_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, null=True, size=None, verbose_name='Rule Build Tags'),
        ),
        migrations.AlterField(
            model_name='graphrule',
            name='rule_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=400), default=list, size=None, verbose_name='Rule Languages'),
        ),
        migrations.AlterField(
            model_name='graphrule',
            name='rule_name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Rule Name'),
        ),
        migrations.AlterField(
            model_name='graphrule',
            name='rule_packages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=list, size=None, verbose_name='Rule Packages'),
        ),
        migrations.AlterField(
            model_name='graphrule',
            name='rule_release_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Release', to_field='release_slug', verbose_name='Release'),
        ),
    ]
