# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cacheapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphrules',
            name='created_by',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='created_by',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='streambranches',
            name='created_by',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
