# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 06:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171009_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reports_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_subject', models.CharField(max_length=200, unique=True)),
                ('report_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('report_updated', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ts_reports',
                'verbose_name': 'Reports',
            },
        ),
        migrations.AddField(
            model_name='packages',
            name='component',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Component'),
        ),
        migrations.AddField(
            model_name='packages',
            name='maintainers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='transplatform_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.TransPlatform', to_field='platform_slug', verbose_name='Translation Platform'),
        ),
    ]
