# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 12:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171110_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='downstream_lastupdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='stats_diff',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releasestream',
            name='relstream_built_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, null=True, size=None, verbose_name='Release Build Tags'),
        ),
        migrations.AddField(
            model_name='releasestream',
            name='relstream_built_tags_lastupdated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='syncstats',
            name='source',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='maintainers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='mapping_lastupdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='transtats_lastupdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='upstream_lastupdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='upstream_latest_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
