# Generated by Django 2.0.1 on 2018-02-06 08:28

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171110_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='downstream_lastupdated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='downstream_latest_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='releasestream',
            name='relstream_built_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, null=True, size=None, verbose_name='Release Build Tags'),
        ),
        migrations.AddField(
            model_name='releasestream',
            name='relstream_built_tags_lastupdated',
            field=models.DateTimeField(null=True),
        ),
    ]
