# Generated by Django 2.0.8 on 2020-07-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cachebuilddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_latest_builds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_latest_builds_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
