# Generated by Django 2.0.8 on 2020-10-06 12:37

from django.conf import settings
from django.db import migrations, models


def update_upstream_job_template(apps, schema_editor):
    if not settings.MIGRATE_INITIAL_DATA:
        return

    JobTemplate = apps.get_model('dashboard', 'JobTemplate')

    JobTemplate.objects.filter(job_template_type="syncupstream").update(
        job_template_params="{package_name,repo_type,repo_branch}",
        job_template_json_str='{"job":{"exception":"raise","execution":"sequential","name":"upstream stats",'
                              '"package":"%PACKAGE_NAME%","return_type":"json","tasks":[{"clone":'
                              '[{"name":"git repo"},{"type":"%REPO_TYPE%"},{"branch":"%REPO_BRANCH%"}]},'
                              '{"filter":[{"name":"files"},{"ext":"PO"}]},{"calculate":"Stats"}],'
                              '"type":"syncupstream"}}'
    )

    JobTemplate.objects.filter(job_template_type="stringchange").update(
        job_template_params="{package_name,release_slug,repo_branch}",
        job_template_json_str='{"job":{"release":"%RELEASE_SLUG%","exception":"raise",'
                              '"execution":"sequential","name":"string change","package":"%PACKAGE_NAME%",'
                              '"return_type":"json","tasks":[{"clone":[{"name":"git repo"},'
                              '{"branch":"%REPO_BRANCH%"},{"recursive":"true"}]},{"generate":[{"name":"POT file"},'
                              '{"domain":"%PACKAGE_NAME%"},'
                              '{"cmd":"cd po && intltool-update --pot --gettext-package=%PACKAGE_NAME%"}]},'
                              '{"download":[{"name": "Platform POT file"}]},'
                              '{"calculate":"Diff"}],"type":"stringchange"}}'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200707_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='upstream_l10n_url',
            field=models.URLField(blank=True, max_length=2000, null=True, unique=True,
                                  verbose_name='Upstream Localization URL'),
        ),
        migrations.RunPython(update_upstream_job_template, reverse_code=migrations.RunPython.noop),
    ]
