# Generated by Django 2.0.3 on 2018-05-23 13:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180301_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_ip', models.GenericIPAddressField()),
                ('visitor_user_agent', models.CharField(max_length=500)),
                ('visitor_accept', models.CharField(blank=True, max_length=500, null=True)),
                ('visitor_encoding', models.CharField(blank=True, max_length=500, null=True)),
                ('visitor_language', models.CharField(blank=True, max_length=500, null=True)),
                ('visitor_host', models.CharField(blank=True, max_length=500, null=True)),
                ('first_visit_time', models.DateTimeField()),
                ('last_visit_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Visitors',
                'db_table': 'ts_visitors',
            },
        ),
        migrations.AddField(
            model_name='syncstats',
            name='stats_processed_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
