# Generated by Django 2.0.8 on 2020-10-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200707_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='upstream_l10n_url',
            field=models.URLField(blank=True, max_length=2000, null=True, unique=True,
                                  verbose_name='Upstream Localization URL'),
        ),
    ]
