# Generated by Django 2.0.3 on 2018-07-02 07:32

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180523_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplates',
            fields=[
                ('job_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_template_type', models.CharField(max_length=100)),
                ('job_template_name', models.CharField(max_length=500)),
                ('job_template_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_template_params', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=list, size=None)),
                ('job_template_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('job_template_last_accessed', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Job Templates',
                'db_table': 'ts_jobtemplates',
            },
        ),
        migrations.AddField(
            model_name='graphrules',
            name='rule_visibility_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_output_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_params_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_visible_on_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_yml_text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='triggered_by',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='languages',
            name='locale_script',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Locale Script'),
        ),
        migrations.AlterField(
            model_name='graphrules',
            name='rule_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='locale_alias',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Locale Alias'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.JobTemplates', verbose_name='Job Template'),
        ),
    ]
