# Generated by Django 2.0.7 on 2018-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180702_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplates',
            name='job_template_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
