# Generated by Django 2.2.24 on 2021-08-30 10:10

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_update_job_templates_20210709'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('pipeline_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('pipeline_config_event', models.CharField(max_length=1000)),
                ('pipeline_config_active', models.BooleanField(default=False)),
                ('pipeline_config_json_str', models.TextField(blank=True, null=True)),
                ('pipeline_config_created_on', models.DateTimeField(null=True)),
                ('pipeline_config_updated_on', models.DateTimeField(null=True)),
                ('pipeline_config_last_accessed', models.DateTimeField(null=True)),
                ('pipeline_config_created_by', models.EmailField(max_length=254, null=True)),
                ('ci_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.CIPipeline', to_field='ci_pipeline_uuid', verbose_name='CI Pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Config',
                'db_table': 'ts_cipipelineconfig',
            },
            bases=(dashboard.models.ModelMixin, models.Model),
        ),
    ]
