# Generated by Django 2.2.24 on 2021-09-29 10:54

import dashboard.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def modify_job_template(apps, schema_editor):

    if not settings.MIGRATE_INITIAL_DATA:
        return

    JobTemplate = apps.get_model('dashboard', 'JobTemplate')

    JobTemplate.objects.filter(job_template_type="dpushtrans").update(
        job_template_json_str='{"job":{"ci_pipeline":"%PIPELINE_UUID%","exception":"raise","execution":"sequential",'
                              '"name":"download and push translations","package":"%PACKAGE_NAME%","return_type":"json",'
                              '"tasks":[{"download":[{"name":"Translation files"},{"target_langs":"%TARGET_LANGS%"},'
                              '{"type":"%REPO_TYPE%"},{"branch":"%REPO_BRANCH%"}]},{"upload":[{"name":"Push files"},'
                              '{"target_langs":"%TARGET_LANGS%"},{"prehook":"skip"},{"posthook":"skip"},'
                              '{"import_settings":"project"},{"update":false},{"prepend_branch":false}]}],'
                              '"type":"dpushtrans"}}'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_update_job_templates_20210709'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('pipeline_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('pipeline_config_event', models.CharField(max_length=1000)),
                ('pipeline_config_active', models.BooleanField(default=False)),
                ('pipeline_config_json_str', models.TextField(unique=True)),
                ('pipeline_config_repo_branches', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=list, size=None, verbose_name='Repo Branches')),
                ('pipeline_config_created_on', models.DateTimeField(null=True)),
                ('pipeline_config_updated_on', models.DateTimeField(null=True)),
                ('pipeline_config_last_accessed', models.DateTimeField(null=True)),
                ('pipeline_config_created_by', models.EmailField(max_length=254, null=True)),
                ('ci_pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.CIPipeline', verbose_name='CI Pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Config',
                'db_table': 'ts_cipipelineconfig',
            },
            bases=(dashboard.models.ModelMixin, models.Model),
        ),
        migrations.RunPython(modify_job_template, reverse_code=migrations.RunPython.noop),
    ]
