# Generated by Django 2.2.28 on 2022-05-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_pipelineconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipipeline',
            name='ci_pipeline_auto_create_config',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Create default configurations'),
        ),
        migrations.AddField(
            model_name='cipipeline',
            name='ci_pipeline_default_branch',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Default Branch'),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='pipeline_config_is_default',
            field=models.BooleanField(default=False),
        ),
    ]
