# Generated by Django 2.2.28 on 2022-06-06 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20220502_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineconfig',
            name='pipeline_config_target_lang',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=list, size=None, verbose_name='Repo Target Langs'),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='pipeline_config_json_str',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='pipelineconfig',
            constraint=models.UniqueConstraint(fields=('pipeline_config_json_str', 'pipeline_config_repo_branches'), name='unique_pipeline_config'),
        ),
    ]
