# Generated by Django 2.2.13 on 2021-06-04 07:44

from django.conf import settings
from django.db import migrations, models


def modify_ci_platform(apps, schema_editor):

    if not settings.MIGRATE_INITIAL_DATA:
        return

    Platform = apps.get_model('dashboard', 'Platform')

    Platform.objects.filter(platform_slug="MSRCPUB").update(
        engine_name="phrase"
    )


def modify_job_template(apps, schema_editor):

    if not settings.MIGRATE_INITIAL_DATA:
        return

    JobTemplate = apps.get_model('dashboard', 'JobTemplate')

    JobTemplate.objects.filter(job_template_type="pushtrans").update(
        job_template_name="Clone and Push Translations"
    )


def modify_ci_platform_reverse(apps, schema_editor):

    if not settings.MIGRATE_INITIAL_DATA:
        return

    Platform = apps.get_model('dashboard', 'Platform')

    Platform.objects.filter(platform_slug="MSRCPUB").update(
        engine_name="memsource"
    )


def modify_job_template_reverse(apps, schema_editor):

    if not settings.MIGRATE_INITIAL_DATA:
        return

    JobTemplate = apps.get_model('dashboard', 'JobTemplate')

    JobTemplate.objects.filter(job_template_type="pushtrans").update(
        job_template_name="Push Translations"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20220606_0722'),
    ]

    operations = [
        migrations.RunPython(modify_ci_platform, reverse_code=modify_ci_platform_reverse),
        migrations.RunPython(modify_job_template, reverse_code=modify_job_template_reverse),
    ]
