# Generated by Django 2.2.28 on 2022-11-22 11:24

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_add_job_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformProjectTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_template_json_str', models.TextField(blank=True, null=True)),
                ('default_project_template', models.CharField(blank=True, max_length=200, null=True, verbose_name='Project Template UID')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Platform', to_field='platform_slug', verbose_name='Translation Platform')),
            ],
            options={
                'verbose_name': 'Platform Project Templates',
                'db_table': 'ts_platformprojecttemplates',
            },
            bases=(dashboard.models.ModelMixin, models.Model),
        ),
    ]
