# Generated by Django 2.2.24 on 2021-07-09 07:22

from django.conf import settings
from django.db import migrations, models


def modify_job_templates(apps, schema_editor):

    if not settings.MIGRATE_INITIAL_DATA:
        return

    JobTemplate = apps.get_model('dashboard', 'JobTemplate')

    JobTemplate.objects.filter(job_template_type="pushtrans").update(
        job_template_json_str='{"job":{"ci_pipeline":"%PIPELINE_UUID%","exception":"raise","execution":"sequential",'
                              '"name":"push translations","package":"%PACKAGE_NAME%","return_type":"json",'
                              '"tasks":[{"clone":[{"name":"git repo"},{"type":"%REPO_TYPE%"},'
                              '{"branch":"%REPO_BRANCH%"},{"recursive":false}]},{"filter":[{"name":"files"},'
                              '{"domain":"%PACKAGE_NAME%"},{"ext":"PO"},{"dir":""}]},{"upload":[{"name":"Push files"},'
                              '{"target_langs":"%TARGET_LANGS%"},{"prehook":"skip"},{"posthook":"skip"},'
                              '{"import_settings":"project"},{"update":false},{"prepend_branch":false},'
                              '{"prepend_package":false}]}],"type":"pushtrans"}}'
    )

    JobTemplate.objects.filter(job_template_type="pulltrans").update(
        job_template_json_str='{"job":{"ci_pipeline":"%PIPELINE_UUID%","exception":"raise","execution":"sequential",'
                              '"name":"pull translations","package":"%PACKAGE_NAME%","return_type":"json",'
                              '"tasks":[{"download":[{"name":"Pull translations"},{"target_langs":"%TARGET_LANGS%"},'
                              '{"workflow_step":"%WORKFLOW_STEP%"},{"prepend_branch":false},'
                              '{"prepend_package":false}]},{"upload":[{"name":"Submit translations"},'
                              '{"type":"%REPO_TYPE%"},{"branch":"%REPO_BRANCH%"},{"conflicts":"replace-translated"},'
                              '{"method":"translate"}]}],"type":"pulltrans"}}'
    )

    JobTemplate.objects.filter(job_template_type="dpushtrans").update(
        job_template_json_str='{"job":{"ci_pipeline":"%PIPELINE_UUID%","exception":"raise","execution":"sequential",'
                              '"name":"download and push translations","package":"%PACKAGE_NAME%","return_type":"json",'
                              '"tasks":[{"download":[{"name":"Translation files"},{"target_langs":"%TARGET_LANGS%"},'
                              '{"type":"%REPO_TYPE%"},{"branch":"%REPO_BRANCH%"}]},{"upload":[{"name":"Push files"},'
                              '{"target_langs":"%TARGET_LANGS%"},{"prehook":"skip"},{"posthook":"skip"},'
                              '{"import_settings":"project"},{"update":false},{"prepend_branch":false},'
                              '{"prepend_package":false}]}],"type":"dpushtrans"}}'
    )

    JobTemplate.objects.filter(job_template_type="pulltransmerge").update(
        job_template_json_str='{"job":{"ci_pipeline":"%PIPELINE_UUID%","exception":"raise","execution":"sequential",'
                              '"name":"pull translations and request merge","package":"%PACKAGE_NAME%",'
                              '"return_type":"json","tasks":[{"clone":[{"name":"git repo"},{"type":"%REPO_TYPE%"},'
                              '{"branch":"%REPO_BRANCH%"},{"recursive":false},{"fork":true}]},'
                              '{"download":[{"name":"Pull translated files"},{"target_langs":"%TARGET_LANGS%"},'
                              '{"workflow_step":"%WORKFLOW_STEP%"},{"prehook":"skip"},{"posthook":"skip"},'
                              '{"prepend_branch":false},{"prepend_package":false}]},'
                              '{"copy":[{"name":"Downloaded files"},{"dir":"%COPY_DIR%"}]},'
                              '{"pullrequest":[{"name":"git repo"},{"type":"%REPO_TYPE%"},'
                              '{"branch":"%REPO_BRANCH%"}]}],"type":"pulltransmerge"}}'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_platformprojecttemplates'),
    ]

    operations = [
        migrations.RunPython(modify_job_templates, reverse_code=migrations.RunPython.noop),
    ]
